package barbearia;


/**
* barbearia/Barbeiro.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Barbearia.idl
* Terça-feira, 9 de Junho de 2009 09h12min53s BRT
*/

public interface Barbeiro extends BarbeiroOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Barbeiro
