package barbearia;


/**
* barbearia/BarbeiroOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from barbearia.idl
* Quarta-feira, 24 de Junho de 2009 09h34min58s BRT
*/

public interface BarbeiroOperations 
{
  boolean cortarBarba (short id);
  boolean cortarCabelo (short id);
  boolean cortarBigode (short id);
} // interface BarbeiroOperations
