module barbearia {

  struct Mensagem {
     short id;
     string rc;
     short cont;
  };

  interface Cliente {
    oneway void Concorrer(in Mensagem msg);
    oneway void msgOK(in short id);
  };

  interface Barbeiro {
    boolean cortarBarba(in short id);
    boolean cortarCabelo(in short id);
    boolean cortarBigode(in short id);
  };

};