package barbearia;


/**
* barbearia/BarbeiroOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from barbearia.idl
* Terça-feira, 9 de Junho de 2009 09h12min53s BRT
*/

public interface BarbeiroOperations 
{
  boolean cortarBarba ();
  boolean cortarCabelo ();
  boolean cortarBigode ();
} // interface BarbeiroOperations
