package barbearia;


/**
* barbearia/Barbeiro.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from barbearia.idl
* Quarta-feira, 24 de Junho de 2009 09h34min58s BRT
*/

public interface Barbeiro extends BarbeiroOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Barbeiro
