package barbearia;

/**
* barbearia/ClienteHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from barbearia.idl
* Terça-feira, 9 de Junho de 2009 09h12min53s BRT
*/

public final class ClienteHolder implements org.omg.CORBA.portable.Streamable
{
  public barbearia.Cliente value = null;

  public ClienteHolder ()
  {
  }

  public ClienteHolder (barbearia.Cliente initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = barbearia.ClienteHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    barbearia.ClienteHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return barbearia.ClienteHelper.type ();
  }

}
