package barbearia;


/**
* barbearia/ClienteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from barbearia.idl
* Terça-feira, 9 de Junho de 2009 09h12min53s BRT
*/

public interface ClienteOperations 
{
  void Concorrer (barbearia.Mensagem msg);
  void msgOK (short id);
} // interface ClienteOperations
