package barbearia;


/**
* barbearia/MensagemHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from barbearia.idl
* Terça-feira, 9 de Junho de 2009 09h12min53s BRT
*/

abstract public class MensagemHelper
{
  private static String  _id = "IDL:barbearia/Mensagem/Mensagem:1.0";

  public static void insert (org.omg.CORBA.Any a, barbearia.Mensagem that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static barbearia.Mensagem extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[0] = new org.omg.CORBA.StructMember (
            "id",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "rc",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[2] = new org.omg.CORBA.StructMember (
            "cont",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (barbearia.MensagemHelper.id (), "Mensagem", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static barbearia.Mensagem read (org.omg.CORBA.portable.InputStream istream)
  {
    barbearia.Mensagem value = new barbearia.Mensagem ();
    value.id = istream.read_short ();
    value.rc = istream.read_string ();
    value.cont = istream.read_short ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, barbearia.Mensagem value)
  {
    ostream.write_short (value.id);
    ostream.write_string (value.rc);
    ostream.write_short (value.cont);
  }

}
