package barbearia;


/**
* barbearia/Mensagem.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from barbearia.idl
* Terça-feira, 9 de Junho de 2009 09h12min53s BRT
*/

public final class Mensagem implements org.omg.CORBA.portable.IDLEntity
{
  public short id = (short)0;
  public String rc = null;
  public short cont = (short)0;

  public Mensagem ()
  {
  } // ctor

  public Mensagem (short _id, String _rc, short _cont)
  {
    id = _id;
    rc = _rc;
    cont = _cont;
  } // ctor

} // class Mensagem
